Transform: AWS::Serverless-2016-10-31
Description: Golang lambda functions for S3 Bucket operation

Globals:
  Function:
    Timeout: 15

Parameters:
  BucketName:
    Type: String
    Default: ''

  DynamoTableName:
    Type: String
    Default: ''

Resources:
  S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref BucketName

  MetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName

      AttributeDefinitions:
        - AttributeName: filename
          AttributeType: S
      KeySchema:
        - AttributeName: filename
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  GoLambdaFunctions:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev

  GetAllMetadataFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "get_all_metadata"
      CodeUri: ./cmd/functions/get_all_metadata/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          DYNAMO_TABLE: !Ref DynamoTableName
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref GoLambdaFunctions
            Path: /metadata
            Method: GET

  GetAudioByIDFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "get_audio_by_id"
      CodeUri: ./cmd/functions/get_audio_by_id/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BucketName
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref GoLambdaFunctions
            Path: /audio/{filename}
            Method: GET

  StoreAudioFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "store_audio"
      CodeUri: ./cmd/functions/store_audio/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BucketName
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref GoLambdaFunctions
            Path: /audio
            Method: POST

  StoreMetadataFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: "store_metadata"
      CodeUri: ./cmd/functions/store_metadata/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BucketName
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          DYNAMO_TABLE: !Ref DynamoTableName
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref GoLambdaFunctions
            Path: /metadata
            Method: POST
